name: Issues Troubleshooting
on:
  issues:
    types:
      - opened
      - labeled
      - reopened
      - reopened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@main
        id: genRequest
        with:
          url: 'http://mandoguru.com:8000/v1.0.0/gen_prog/'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "KEY": "MqQVfJ6Fq1umZnUI7ZuaycciCjxi3gM0"}'
          data: '{"idea": "${{ github.event.issue.body }}, "n_rounds": 5}'
          preventFailureOnNoResponse: 'true'
  
      - name: Push Project
        id: initRequest
        with:
          url: 'http://mandoguru.com:8000/v1.0.0/init_repo/'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "KEY": "MqQVfJ6Fq1umZnUI7ZuaycciCjxi3gM0"}'
          data: |
            '{"id": "01", \
              "name": ${{ fromJson(steps.genRequest.outputs.response).repo_name }}, \
              "local": ${{ fromJson(steps.genRequest.outputs.response).repo_name }}, \ 
              "remote_url": ${{ github.server_url }}/${{ github.repository }}, \ 
              "remote_name": "origin", \ 
              "branch": "master", \
              "commit_message": "Init commit"}'
          preventFailureOnNoResponse: 'true'
  
