name: Issues Troubleshooting
on:
  issues:
    types:
      - opened
      - labeled
      - reopened
      - reopened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
    
      # - name: Local Action
      #   id: test-action
      #   uses: minhnn-tiny/startup-typescript-action@main # Commit with the `v1` tag
      #   with:
      #     milliseconds: 1000
      # - name: Print Output
      #   id: output
      #   run: echo "${{ steps.test-action.outputs.time }}"
        
      # - name: Deploy Stage
      #   uses: fjogeleit/http-request-action@main
      #   id: genRequest
      #   with:
      #     url: 'http://mandoguru.com:8000/v1.0.0/gen_prog/'
      #     method: 'POST'
      #     customHeaders: '{"Content-Type": "application/json", "KEY": "MqQVfJ6Fq1umZnUI7ZuaycciCjxi3gM0"}'
      #     data: '{"idea": "${{ github.event.issue.body }}"}'
      #     preventFailureOnNoResponse: 'true'
      # - name: Push Project
      #   id: initRequest
      #   with:
      #     url: 'http://mandoguru.com:8000/v1.0.0/init_repo/'
      #     method: 'POST'
      #     customHeaders: '{"Content-Type": "application/json", "KEY": "MqQVfJ6Fq1umZnUI7ZuaycciCjxi3gM0"}'
      #     data: |
      #       '{"id": "01", \
      #         "name": ${{ fromJson(steps.genRequest.outputs.response).repo_name }}, \
      #         "local": ${{ fromJson(steps.genRequest.outputs.response).repo_name }}, \ 
      #         "remote_url": "https://github.com/Auto-Actions/test_3", \ 
      #         "remote_name": "origin", \ 
      #         "branch": "master", \
      #         "commit_message": "Init commit"}'
      #     preventFailureOnNoResponse: 'true'
      # - name: Show Response
      #   run: |
      #     echo ${{ steps.genRequest.outputs.response }}
      #     echo ${{ steps.genRequest.outputs.headers }}
      #     echo ${{ fromJson(steps.genRequest.outputs.response).repo_name }}
      - name: Retrieve Repo Address
        id: repoURL
        run: echo ${{ github.server_url }}/${{ github.repository }}
